import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link';
import config from '../../config';
import styles from '../../styles/Admin.module.css'

const Home: NextPage = ({ jobs }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>CloudJob</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="container">
          <header className="d-flex justify-content-center py-3">
            <ul className="nav nav-pills">
              <li className="nav-item">
                  <Link href="/">
                    <a className="nav-link">Positions</a>
                  </Link>
                </li>
              <li className="nav-item"><a href="/admin" className="nav-link active" aria-current="page">Admin</a></li>
            </ul>
          </header>
          <ul className="list-group">
            {jobs ? 
              jobs.map((job, i: number) => <li key={i} className="list-group-item"><a href={`/position/${job.id}`}>{job.name}</a></li>) 
            : 'Loading'}
          </ul>
          
        </div>
      </main>
    </div>
  )
}

export async function getServerSideProps(): Promise<Record<string, unknown>> {
  const res = await fetch(`${config.baseUrl}/api/positions/`)
  const post = await res.json();
  
  return {
    props: { jobs: await Promise.all(post.map(async (id: string) => {
      return { id, ...(await (await fetch(`${config.baseUrl}/api/positions/${id}`, { body: JSON.stringify({admin_key: "AdminKey"})})).json()) }; 
    }))}, // will be passed to the page component as props
  }
}

export default Home
