import type { NextPage } from 'next'
import { useRouter } from 'next/router';
import Head from 'next/head'
import Link from 'next/link';
import ReactMarkdown from 'react-markdown';
import '../../styles/PositionIndex.module.css'
import { useEffect, useState } from 'react';
import config from '../../config';

const PositionIndex: NextPage = () => {
  const router = useRouter()
  const { id } = router.query;
  
  const [data, setData] = useState({});

  const [formData, setFormData] = useState({
    name: "",
    experience: "",
    education: "",
    application: ""
  });
  useEffect(() => {
    const run = async () => {
      try {
        const res = await fetch(`${config.baseUrl}/api/positions/${id}`);
        const json = await res.json();
        if (json.error) {
          window.location.href = '/';
        }
        setData(json);
      } catch (e) {
        window.location.href = '/';
      }
    }
    run();
  }, [id]);
  return (
    <div>
      <Head>
        <title>CloudJob</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container">
          <header className="d-flex justify-content-center py-3">
            <ul className="nav nav-pills">
              <li className="nav-item">
                  <Link href="/">
                    <a className="nav-link active" aria-current="page">Positions</a>
                  </Link>
                </li>
              <li className="nav-item">
                <Link href="/admin">
                  <a className="nav-link">Admin</a>
                </Link>
              </li>
            </ul>
          </header>
          <h1>{(data as {name: string;}).name}</h1>
          <ReactMarkdown>{(data as {description: string;}).description}</ReactMarkdown>
          <hr />
          <div id="apply">
            <h2>Apply to this position</h2>
            <form>
                <label className="form-check-label" htmlFor="exampleCheck1">Name</label>
                <input type="text" className="form-control" onChange={(e) => setFormData({...formData, name: e.target.value})}/>
                <label className="form-check-label" htmlFor="exampleCheck1">Experience</label>
                <textarea className="form-control"onChange={(e) => setFormData({...formData, experience: e.target.value})} /> 
                <label className="form-check-label" htmlFor="exampleCheck1">Education</label>
                <textarea className="form-control" onChange={(e) => setFormData({...formData, education: e.target.value})} /> 
                <label className="form-check-label" htmlFor="exampleCheck1">Application</label>
                <textarea className="form-control" onChange={(e) => setFormData({...formData, application: e.target.value})} /> 
            </form>
            <br />
            <button className="btn btn-primary" onClick={async () => {
              if(formData.name === '' || formData.application === '' || formData.experience === '' || formData.education === '') {
                alert("Fill all fields.");
                return;
              }
              await fetch(`${config.baseUrl}/api/positions/${id}`, {
                method: 'POST',
                body: JSON.stringify(formData)
              })
              document.getElementById("apply")?.classList.add('hidden');
              document.getElementById("applied")?.classList.remove('hidden');
            }}>Apply</button>
          </div>
          <div id="applied" className="hidden">
            <h2>Thank you for applying!</h2>
          </div>
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps({ params }: {params: {id:string;}}): Promise<Record<string, unknown>> {
  // params contains the post `id`.
  const res = await fetch(`${config.baseUrl}/api/positions/${params.id}`)
  const post = await res.json()

  // Pass post data to the page via props
  return { props: { post } }
}

export async function getStaticPaths(): Promise<Record<string, unknown>> {
  const res = await fetch(`${config.baseUrl}/api/positions`)
  const data = await res.json()
  return {
    paths: data.map((id: string) => {
      return { params: { id } };
    }),
    fallback: false,
  };
}

export default PositionIndex;
